### ISSUE TITLE
High score does not update upon game completion

### ISSUE THREAD

**Issue by EddieFed** [Murf-o/cryptarch-quiz#11]
The score only refreshes when manually refreshing the page, it does not dynamically update

**Comment by Murf-o** [comment]
Ahh! 
Good catch, I'll take a peek.

**Comment by Murf-o** [comment]
Awesome, should be fixed now via this [Commit ](https://github.com/Murf-o/cryptarch-quiz/commit/a0c5aab8135640b5e99436cd263b5ddb0d10dfdf)

P.S. use port 8000 now :)
